CREATE TABLE
IF NOT EXISTS `user`(
   `id` INT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR
(100) NOT NULL,
   `age` VARCHAR
(40) NOT NULL,
   `birthday` DATE,
   PRIMARY KEY
( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8