CREATE TABLE
IF NOT EXISTS `article`
(
   `id` INT UNSIGNED AUTO_INCREMENT,
   `content` LONGTEXT NOT NULL,
   `crt_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP comment '创建时间',
   `upd_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP comment '更新时间',
   `user_id` INT,
   PRIMARY KEY
( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8

